version: 0.2

env:
  variables:
    CODE_SRC_DIR: "application/terraform"
    TF_VERSION: "1.4.0"

phases:
  install:
    commands:
      - "bash ${CODEBUILD_SRC_DIR}/setup/scripts/codebuild-terraform-install.sh ${TF_VERSION}"
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}/${ENVIRONMENT}"
      - 'terraform init -backend-config="../configs/production.tfbackend"'
      - 'terraform apply -input=false -var-file="../configs/${ENVIRONMENT}.tfvars" -var-file="../configs/shared.tfvars" -auto-approve'
